package org.javautil.persist.hibernate.hbm;

// Generated May 11, 2009 2:15:28 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * Ticket generated by hbm2java
 */
public class Ticket implements java.io.Serializable {

	private String ticketNo;
	private String applicationName;
	private String userSessionIdHash;
	private String ipAddress;
	private Date authDttm;
	private Date expireDttm;
	private Date logoutDttm;

	public Ticket() {
	}

	public Ticket(Date authDttm) {
		this.authDttm = authDttm;
	}

	public Ticket(String applicationName, String userSessionIdHash,
			String ipAddress, Date authDttm, Date expireDttm, Date logoutDttm) {
		this.applicationName = applicationName;
		this.userSessionIdHash = userSessionIdHash;
		this.ipAddress = ipAddress;
		this.authDttm = authDttm;
		this.expireDttm = expireDttm;
		this.logoutDttm = logoutDttm;
	}

	public String getTicketNo() {
		return this.ticketNo;
	}

	public void setTicketNo(String ticketNo) {
		this.ticketNo = ticketNo;
	}

	public String getApplicationName() {
		return this.applicationName;
	}

	public void setApplicationName(String applicationName) {
		this.applicationName = applicationName;
	}

	public String getUserSessionIdHash() {
		return this.userSessionIdHash;
	}

	public void setUserSessionIdHash(String userSessionIdHash) {
		this.userSessionIdHash = userSessionIdHash;
	}

	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	public Date getAuthDttm() {
		return this.authDttm;
	}

	public void setAuthDttm(Date authDttm) {
		this.authDttm = authDttm;
	}

	public Date getExpireDttm() {
		return this.expireDttm;
	}

	public void setExpireDttm(Date expireDttm) {
		this.expireDttm = expireDttm;
	}

	public Date getLogoutDttm() {
		return this.logoutDttm;
	}

	public void setLogoutDttm(Date logoutDttm) {
		this.logoutDttm = logoutDttm;
	}

}