//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.09 at 01:38:12 PM EDT 
//

package org.javautil.xsd.columnmetadata;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for columnType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="columnType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *       &lt;/choice>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="heading" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="columnDisplaySize" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="comments" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="externalFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="attributeName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="workbookFormula" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="excelFormat" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="javaFormat" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="groupName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="horizontalAlignment" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="aggregateFunction" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "columnType")
public class ColumnType {

	@XmlAttribute
	protected String name;
	@XmlAttribute
	protected BigInteger index;
	@XmlAttribute
	protected String heading;
	@XmlAttribute
	protected String label;
	@XmlAttribute
	protected BigInteger columnDisplaySize;
	@XmlAttribute
	protected String comments;
	@XmlAttribute
	protected Boolean externalFlag;
	@XmlAttribute
	protected String attributeName;
	@XmlAttribute
	protected String workbookFormula;
	@XmlAttribute
	protected String excelFormat;
	@XmlAttribute
	protected String javaFormat;
	@XmlAttribute
	protected String groupName;
	@XmlAttribute
	protected String horizontalAlignment;
	@XmlAttribute
	protected String aggregateFunction;

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(final String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the index property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getIndex() {
		return index;
	}

	/**
	 * Sets the value of the index property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setIndex(final BigInteger value) {
		this.index = value;
	}

	/**
	 * Gets the value of the heading property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHeading() {
		return heading;
	}

	/**
	 * Sets the value of the heading property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setHeading(final String value) {
		this.heading = value;
	}

	/**
	 * Gets the value of the label property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLabel() {
		return label;
	}

	/**
	 * Sets the value of the label property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLabel(final String value) {
		this.label = value;
	}

	/**
	 * Gets the value of the columnDisplaySize property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getColumnDisplaySize() {
		return columnDisplaySize;
	}

	/**
	 * Sets the value of the columnDisplaySize property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setColumnDisplaySize(final BigInteger value) {
		this.columnDisplaySize = value;
	}

	/**
	 * Gets the value of the comments property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getComments() {
		return comments;
	}

	/**
	 * Sets the value of the comments property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setComments(final String value) {
		this.comments = value;
	}

	/**
	 * Gets the value of the externalFlag property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isExternalFlag() {
		return externalFlag;
	}

	/**
	 * Sets the value of the externalFlag property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setExternalFlag(final Boolean value) {
		this.externalFlag = value;
	}

	/**
	 * Gets the value of the attributeName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAttributeName() {
		return attributeName;
	}

	/**
	 * Sets the value of the attributeName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAttributeName(final String value) {
		this.attributeName = value;
	}

	/**
	 * Gets the value of the workbookFormula property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getWorkbookFormula() {
		return workbookFormula;
	}

	/**
	 * Sets the value of the workbookFormula property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setWorkbookFormula(final String value) {
		this.workbookFormula = value;
	}

	/**
	 * Gets the value of the excelFormat property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getExcelFormat() {
		return excelFormat;
	}

	/**
	 * Sets the value of the excelFormat property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setExcelFormat(final String value) {
		this.excelFormat = value;
	}

	/**
	 * Gets the value of the javaFormat property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getJavaFormat() {
		return javaFormat;
	}

	/**
	 * Sets the value of the javaFormat property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setJavaFormat(final String value) {
		this.javaFormat = value;
	}

	/**
	 * Gets the value of the groupName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getGroupName() {
		return groupName;
	}

	/**
	 * Sets the value of the groupName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setGroupName(final String value) {
		this.groupName = value;
	}

	/**
	 * Gets the value of the horizontalAlignment property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHorizontalAlignment() {
		return horizontalAlignment;
	}

	/**
	 * Sets the value of the horizontalAlignment property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setHorizontalAlignment(final String value) {
		this.horizontalAlignment = value;
	}

	/**
	 * Gets the value of the aggregateFunction property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAggregateFunction() {
		return aggregateFunction;
	}

	/**
	 * Sets the value of the aggregateFunction property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAggregateFunction(final String value) {
		this.aggregateFunction = value;
	}

}
