package org.javautil.sales.dto;
// Generated Sep 8, 2011 2:57:23 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * GttNumber generated by hbm2java
 */
@Entity
@Table(name="GTT_NUMBER"
    ,schema="PUBLIC"
    ,catalog="SALES"
)
public class GttNumber  implements java.io.Serializable {


     private Integer nbr;

    public GttNumber() {
    }

   
     @SequenceGenerator(name="generator", sequenceName="GTT_NUMBER_NBR_SEQ")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")
    
    @Column(name="NBR", nullable=false, precision=9, scale=0)
    public Integer getNbr() {
        return this.nbr;
    }
    
    public void setNbr(Integer nbr) {
        this.nbr = nbr;
    }




}


