package org.javautil.sales.dto;
// Generated Sep 8, 2011 2:57:23 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductEtlId generated by hbm2java
 */
@Embeddable
public class ProductEtlId  implements java.io.Serializable {


     private int productEtlId;
     private String upc10;
     private String productStatus;
     private String descr;
     private String narrative;

    public ProductEtlId() {
    }

    public ProductEtlId(int productEtlId, String upc10, String productStatus, String descr, String narrative) {
       this.productEtlId = productEtlId;
       this.upc10 = upc10;
       this.productStatus = productStatus;
       this.descr = descr;
       this.narrative = narrative;
    }
   

    @Column(name="PRODUCT_ETL_ID", nullable=false, precision=9, scale=0)
    public int getProductEtlId() {
        return this.productEtlId;
    }
    
    public void setProductEtlId(int productEtlId) {
        this.productEtlId = productEtlId;
    }

    @Column(name="UPC10", nullable=false, length=10)
    public String getUpc10() {
        return this.upc10;
    }
    
    public void setUpc10(String upc10) {
        this.upc10 = upc10;
    }

    @Column(name="PRODUCT_STATUS", nullable=false, length=1)
    public String getProductStatus() {
        return this.productStatus;
    }
    
    public void setProductStatus(String productStatus) {
        this.productStatus = productStatus;
    }

    @Column(name="DESCR", nullable=false, length=50)
    public String getDescr() {
        return this.descr;
    }
    
    public void setDescr(String descr) {
        this.descr = descr;
    }

    @Column(name="NARRATIVE", nullable=false)
    public String getNarrative() {
        return this.narrative;
    }
    
    public void setNarrative(String narrative) {
        this.narrative = narrative;
    }




}


