//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.09 at 01:38:12 PM EDT 
//

package org.javautil.xsd.columnmetadata;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the org.javautil.xsd.columnmetadata package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _Column_QNAME = new QName(
			"http://javautil.org/xsd/ColumnMetadata/", "column");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: org.javautil.xsd.columnmetadata
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link StringType }
	 * 
	 */
	public StringType createStringType() {
		return new StringType();
	}

	/**
	 * Create an instance of {@link NumberType }
	 * 
	 */
	public NumberType createNumberType() {
		return new NumberType();
	}

	/**
	 * Create an instance of {@link DateType }
	 * 
	 */
	public DateType createDateType() {
		return new DateType();
	}

	/**
	 * Create an instance of {@link NumericType }
	 * 
	 */
	public NumericType createNumericType() {
		return new NumericType();
	}

	/**
	 * Create an instance of {@link ColumnType }
	 * 
	 */
	public ColumnType createColumnType() {
		return new ColumnType();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ColumnType }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://javautil.org/xsd/ColumnMetadata/", name = "column")
	public JAXBElement<ColumnType> createColumn(final ColumnType value) {
		return new JAXBElement<ColumnType>(_Column_QNAME, ColumnType.class,
				null, value);
	}

}
