package org.javautil.sales;
// Generated Apr 6, 2009 8:17:12 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private Integer customerId;
     private Salesperson salesperson;
     private String customerStatus;
     private String name;
     private String addr1;
     private String addr2;
     private String city;
     private String state;
     private String zipCd;
     private Integer outsideSalespersonId;
     private Set<Sale> sales = new HashSet<Sale>(0);

    public Customer() {
    }

	
    public Customer(Salesperson salesperson) {
        this.salesperson = salesperson;
    }
    public Customer(Salesperson salesperson, String customerStatus, String name, String addr1, String addr2, String city, String state, String zipCd, Integer outsideSalespersonId, Set<Sale> sales) {
       this.salesperson = salesperson;
       this.customerStatus = customerStatus;
       this.name = name;
       this.addr1 = addr1;
       this.addr2 = addr2;
       this.city = city;
       this.state = state;
       this.zipCd = zipCd;
       this.outsideSalespersonId = outsideSalespersonId;
       this.sales = sales;
    }
   
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }
    public Salesperson getSalesperson() {
        return this.salesperson;
    }
    
    public void setSalesperson(Salesperson salesperson) {
        this.salesperson = salesperson;
    }
    public String getCustomerStatus() {
        return this.customerStatus;
    }
    
    public void setCustomerStatus(String customerStatus) {
        this.customerStatus = customerStatus;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddr1() {
        return this.addr1;
    }
    
    public void setAddr1(String addr1) {
        this.addr1 = addr1;
    }
    public String getAddr2() {
        return this.addr2;
    }
    
    public void setAddr2(String addr2) {
        this.addr2 = addr2;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getZipCd() {
        return this.zipCd;
    }
    
    public void setZipCd(String zipCd) {
        this.zipCd = zipCd;
    }
    public Integer getOutsideSalespersonId() {
        return this.outsideSalespersonId;
    }
    
    public void setOutsideSalespersonId(Integer outsideSalespersonId) {
        this.outsideSalespersonId = outsideSalespersonId;
    }
    public Set<Sale> getSales() {
        return this.sales;
    }
    
    public void setSales(Set<Sale> sales) {
        this.sales = sales;
    }




}


