package org.javautil.sales;
// Generated Apr 6, 2009 8:17:12 PM by Hibernate Tools 3.2.2.GA



/**
 * GttNumber generated by hbm2java
 */
public class GttNumber  implements java.io.Serializable {


     private Integer nbr;

    public GttNumber() {
    }

   
    public Integer getNbr() {
        return this.nbr;
    }
    
    public void setNbr(Integer nbr) {
        this.nbr = nbr;
    }




}


