package org.javautil.sales;
// Generated Apr 6, 2009 8:17:12 PM by Hibernate Tools 3.2.2.GA



/**
 * ProductEtlId generated by hbm2java
 */
public class ProductEtlId  implements java.io.Serializable {


     private Integer productEtlId;
     private String upc10;
     private String productStatus;
     private String descr;
     private String narrative;

    public ProductEtlId() {
    }

    public ProductEtlId(Integer productEtlId, String upc10, String productStatus, String descr, String narrative) {
       this.productEtlId = productEtlId;
       this.upc10 = upc10;
       this.productStatus = productStatus;
       this.descr = descr;
       this.narrative = narrative;
    }
   
    public Integer getProductEtlId() {
        return this.productEtlId;
    }
    
    public void setProductEtlId(Integer productEtlId) {
        this.productEtlId = productEtlId;
    }
    public String getUpc10() {
        return this.upc10;
    }
    
    public void setUpc10(String upc10) {
        this.upc10 = upc10;
    }
    public String getProductStatus() {
        return this.productStatus;
    }
    
    public void setProductStatus(String productStatus) {
        this.productStatus = productStatus;
    }
    public String getDescr() {
        return this.descr;
    }
    
    public void setDescr(String descr) {
        this.descr = descr;
    }
    public String getNarrative() {
        return this.narrative;
    }
    
    public void setNarrative(String narrative) {
        this.narrative = narrative;
    }




}


