package org.javautil.sales;
// Generated Apr 6, 2009 8:17:12 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer productId;
     private String upc10;
     private String productStatus;
     private String descr;
     private String narrative;
     private Set<Sale> sales = new HashSet<Sale>(0);

    public Product() {
    }

	
    public Product(String upc10, String productStatus) {
        this.upc10 = upc10;
        this.productStatus = productStatus;
    }
    public Product(String upc10, String productStatus, String descr, String narrative, Set<Sale> sales) {
       this.upc10 = upc10;
       this.productStatus = productStatus;
       this.descr = descr;
       this.narrative = narrative;
       this.sales = sales;
    }
   
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
    public String getUpc10() {
        return this.upc10;
    }
    
    public void setUpc10(String upc10) {
        this.upc10 = upc10;
    }
    public String getProductStatus() {
        return this.productStatus;
    }
    
    public void setProductStatus(String productStatus) {
        this.productStatus = productStatus;
    }
    public String getDescr() {
        return this.descr;
    }
    
    public void setDescr(String descr) {
        this.descr = descr;
    }
    public String getNarrative() {
        return this.narrative;
    }
    
    public void setNarrative(String narrative) {
        this.narrative = narrative;
    }
    public Set<Sale> getSales() {
        return this.sales;
    }
    
    public void setSales(Set<Sale> sales) {
        this.sales = sales;
    }




}


