package org.javautil.sales;
// Generated Apr 6, 2009 8:17:12 PM by Hibernate Tools 3.2.2.GA



/**
 * ProductEtl generated by hbm2java
 */
public class ProductEtl  implements java.io.Serializable {


     private ProductEtlId id;

    public ProductEtl() {
    }

    public ProductEtl(ProductEtlId id) {
       this.id = id;
    }
   
    public ProductEtlId getId() {
        return this.id;
    }
    
    public void setId(ProductEtlId id) {
        this.id = id;
    }




}


