package org.javautil.sales;
// Generated Apr 6, 2009 8:17:12 PM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Sale generated by hbm2java
 */
public class Sale  implements java.io.Serializable {


     private Integer saleId;
     private Product product;
     private Customer customer;
     private Date shipDt;
     private BigDecimal qty;

    public Sale() {
    }

    public Sale(Product product, Customer customer, Date shipDt, BigDecimal qty) {
       this.product = product;
       this.customer = customer;
       this.shipDt = shipDt;
       this.qty = qty;
    }
   
    public Integer getSaleId() {
        return this.saleId;
    }
    
    public void setSaleId(Integer saleId) {
        this.saleId = saleId;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Date getShipDt() {
        return this.shipDt;
    }
    
    public void setShipDt(Date shipDt) {
        this.shipDt = shipDt;
    }
    public BigDecimal getQty() {
        return this.qty;
    }
    
    public void setQty(BigDecimal qty) {
        this.qty = qty;
    }




}


