package org.javautil.sales;
// Generated Apr 6, 2009 8:17:12 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Salesperson generated by hbm2java
 */
public class Salesperson  implements java.io.Serializable {


     private Integer salespersonId;
     private String displayName;
     private String firstName;
     private String lastName;
     private Set<Customer> customers = new HashSet<Customer>(0);

    public Salesperson() {
    }

    public Salesperson(String displayName, String firstName, String lastName, Set<Customer> customers) {
       this.displayName = displayName;
       this.firstName = firstName;
       this.lastName = lastName;
       this.customers = customers;
    }
   
    public Integer getSalespersonId() {
        return this.salespersonId;
    }
    
    public void setSalespersonId(Integer salespersonId) {
        this.salespersonId = salespersonId;
    }
    public String getDisplayName() {
        return this.displayName;
    }
    
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Set<Customer> getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set<Customer> customers) {
        this.customers = customers;
    }




}


