package org.javautil.mp3;

// Generated Jan 14, 2011 1:36:15 AM by Hibernate Tools 3.2.2.GA

/**
 * ArtistAlias generated by hbm2java
 */
public class ArtistAlias implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer artistAliasId;
	private Artist artist;
	private String artistAlias;
	private String statusCd;

	public ArtistAlias() {
	}

	public ArtistAlias(final String artistAlias) {
		this.artistAlias = artistAlias;
	}

	public ArtistAlias(final Artist artist, final String artistAlias,
			final String statusCd) {
		this.artist = artist;
		this.artistAlias = artistAlias;
		this.statusCd = statusCd;
	}

	public Integer getArtistAliasId() {
		return this.artistAliasId;
	}

	public void setArtistAliasId(final Integer artistAliasId) {
		this.artistAliasId = artistAliasId;
	}

	public Artist getArtist() {
		return this.artist;
	}

	public void setArtist(final Artist artist) {
		this.artist = artist;
	}

	public String getArtistAlias() {
		return this.artistAlias;
	}

	public void setArtistAlias(final String artistAlias) {
		this.artistAlias = artistAlias;
	}

	public String getStatusCd() {
		return this.statusCd;
	}

	public void setStatusCd(final String statusCd) {
		this.statusCd = statusCd;
	}

}
