package org.javautil.mp3;

// Generated Jan 14, 2011 1:36:15 AM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Artist generated by hbm2java
 */
public class Artist implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer artistId;
	private String artistName;
	private Set<ArtistAlias> artistAliases = new HashSet<ArtistAlias>(0);

	public Artist() {
	}

	public Artist(final String artistName, final Set<ArtistAlias> artistAliases) {
		this.artistName = artistName;
		this.artistAliases = artistAliases;
	}

	public Integer getArtistId() {
		return this.artistId;
	}

	public void setArtistId(final Integer artistId) {
		this.artistId = artistId;
	}

	public String getArtistName() {
		return this.artistName;
	}

	public void setArtistName(final String artistName) {
		this.artistName = artistName;
	}

	public Set<ArtistAlias> getArtistAliases() {
		return this.artistAliases;
	}

	public void setArtistAliases(final Set<ArtistAlias> artistAliases) {
		this.artistAliases = artistAliases;
	}

}
