package org.javautil.sales.dto;
// Generated Sep 8, 2011 2:57:23 PM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CustomerSaleProductId generated by hbm2java
 */
@Embeddable
public class CustomerSaleProductId  implements java.io.Serializable {


     private String name;
     private String addr1;
     private String addr2;
     private String city;
     private String state;
     private String zipCd;
     private String upc10;
     private String productStatus;
     private String productDescr;
     private String narrative;
     private Integer insideSalespersonId;
     private String insideRepDisplayName;
     private String insideRepFirstName;
     private String insideRepLastName;
     private Long saleId;
     private Date shipDt;
     private BigDecimal qty;
     private Integer productId;
     private Integer customerId;

    public CustomerSaleProductId() {
    }

    public CustomerSaleProductId(String name, String addr1, String addr2, String city, String state, String zipCd, String upc10, String productStatus, String productDescr, String narrative, Integer insideSalespersonId, String insideRepDisplayName, String insideRepFirstName, String insideRepLastName, Long saleId, Date shipDt, BigDecimal qty, Integer productId, Integer customerId) {
       this.name = name;
       this.addr1 = addr1;
       this.addr2 = addr2;
       this.city = city;
       this.state = state;
       this.zipCd = zipCd;
       this.upc10 = upc10;
       this.productStatus = productStatus;
       this.productDescr = productDescr;
       this.narrative = narrative;
       this.insideSalespersonId = insideSalespersonId;
       this.insideRepDisplayName = insideRepDisplayName;
       this.insideRepFirstName = insideRepFirstName;
       this.insideRepLastName = insideRepLastName;
       this.saleId = saleId;
       this.shipDt = shipDt;
       this.qty = qty;
       this.productId = productId;
       this.customerId = customerId;
    }
   

    @Column(name="NAME", nullable=false, length=30)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Column(name="ADDR_1", nullable=false, length=30)
    public String getAddr1() {
        return this.addr1;
    }
    
    public void setAddr1(String addr1) {
        this.addr1 = addr1;
    }

    @Column(name="ADDR_2", nullable=false, length=30)
    public String getAddr2() {
        return this.addr2;
    }
    
    public void setAddr2(String addr2) {
        this.addr2 = addr2;
    }

    @Column(name="CITY", nullable=false, length=25)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    @Column(name="STATE", nullable=false, length=2)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    @Column(name="ZIP_CD", nullable=false, length=10)
    public String getZipCd() {
        return this.zipCd;
    }
    
    public void setZipCd(String zipCd) {
        this.zipCd = zipCd;
    }

    @Column(name="UPC10", nullable=false, length=10)
    public String getUpc10() {
        return this.upc10;
    }
    
    public void setUpc10(String upc10) {
        this.upc10 = upc10;
    }

    @Column(name="PRODUCT_STATUS", nullable=false, length=1)
    public String getProductStatus() {
        return this.productStatus;
    }
    
    public void setProductStatus(String productStatus) {
        this.productStatus = productStatus;
    }

    @Column(name="PRODUCT_DESCR", nullable=false, length=50)
    public String getProductDescr() {
        return this.productDescr;
    }
    
    public void setProductDescr(String productDescr) {
        this.productDescr = productDescr;
    }

    @Column(name="NARRATIVE", nullable=false)
    public String getNarrative() {
        return this.narrative;
    }
    
    public void setNarrative(String narrative) {
        this.narrative = narrative;
    }

    @Column(name="INSIDE_SALESPERSON_ID", nullable=false, precision=9, scale=0)
    public Integer getInsideSalespersonId() {
        return this.insideSalespersonId;
    }
    
    public void setInsideSalespersonId(Integer insideSalespersonId) {
        this.insideSalespersonId = insideSalespersonId;
    }

    @Column(name="INSIDE_REP__DISPLAY_NAME", nullable=false, length=40)
    public String getInsideRepDisplayName() {
        return this.insideRepDisplayName;
    }
    
    public void setInsideRepDisplayName(String insideRepDisplayName) {
        this.insideRepDisplayName = insideRepDisplayName;
    }

    @Column(name="INSIDE_REP_FIRST_NAME", nullable=false, length=16)
    public String getInsideRepFirstName() {
        return this.insideRepFirstName;
    }
    
    public void setInsideRepFirstName(String insideRepFirstName) {
        this.insideRepFirstName = insideRepFirstName;
    }

    @Column(name="INSIDE_REP_LAST_NAME", nullable=false, length=20)
    public String getInsideRepLastName() {
        return this.insideRepLastName;
    }
    
    public void setInsideRepLastName(String insideRepLastName) {
        this.insideRepLastName = insideRepLastName;
    }

    @Column(name="SALE_ID", nullable=false, precision=18, scale=0)
    public Long getSaleId() {
        return this.saleId;
    }
    
    public void setSaleId(Long saleId) {
        this.saleId = saleId;
    }

    @Column(name="SHIP_DT", nullable=false, length=8)
    public Date getShipDt() {
        return this.shipDt;
    }
    
    public void setShipDt(Date shipDt) {
        this.shipDt = shipDt;
    }

    @Column(name="QTY", nullable=false, precision=13, scale=5)
    public BigDecimal getQty() {
        return this.qty;
    }
    
    public void setQty(BigDecimal qty) {
        this.qty = qty;
    }

    @Column(name="PRODUCT_ID", nullable=false, precision=9, scale=0)
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    @Column(name="CUSTOMER_ID", nullable=false, precision=9, scale=0)
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }




}


