package org.javautil.sales.dto;
// Generated Sep 8, 2011 2:57:23 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CustomerSaleProduct generated by hbm2java
 */
@Entity
@Table(name="CUSTOMER_SALE_PRODUCT"
    ,schema="PUBLIC"
    ,catalog="SALES"
)
public class CustomerSaleProduct  implements java.io.Serializable {


     private CustomerSaleProductId id;

    public CustomerSaleProduct() {
    }

    public CustomerSaleProduct(CustomerSaleProductId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="name", column=@Column(name="NAME", nullable=false, length=30) ), 
        @AttributeOverride(name="addr1", column=@Column(name="ADDR_1", nullable=false, length=30) ), 
        @AttributeOverride(name="addr2", column=@Column(name="ADDR_2", nullable=false, length=30) ), 
        @AttributeOverride(name="city", column=@Column(name="CITY", nullable=false, length=25) ), 
        @AttributeOverride(name="state", column=@Column(name="STATE", nullable=false, length=2) ), 
        @AttributeOverride(name="zipCd", column=@Column(name="ZIP_CD", nullable=false, length=10) ), 
        @AttributeOverride(name="upc10", column=@Column(name="UPC10", nullable=false, length=10) ), 
        @AttributeOverride(name="productStatus", column=@Column(name="PRODUCT_STATUS", nullable=false, length=1) ), 
        @AttributeOverride(name="productDescr", column=@Column(name="PRODUCT_DESCR", nullable=false, length=50) ), 
        @AttributeOverride(name="narrative", column=@Column(name="NARRATIVE", nullable=false) ), 
        @AttributeOverride(name="insideSalespersonId", column=@Column(name="INSIDE_SALESPERSON_ID", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="insideRepDisplayName", column=@Column(name="INSIDE_REP__DISPLAY_NAME", nullable=false, length=40) ), 
        @AttributeOverride(name="insideRepFirstName", column=@Column(name="INSIDE_REP_FIRST_NAME", nullable=false, length=16) ), 
        @AttributeOverride(name="insideRepLastName", column=@Column(name="INSIDE_REP_LAST_NAME", nullable=false, length=20) ), 
        @AttributeOverride(name="saleId", column=@Column(name="SALE_ID", nullable=false, precision=18, scale=0) ), 
        @AttributeOverride(name="shipDt", column=@Column(name="SHIP_DT", nullable=false, length=8) ), 
        @AttributeOverride(name="qty", column=@Column(name="QTY", nullable=false, precision=13, scale=5) ), 
        @AttributeOverride(name="productId", column=@Column(name="PRODUCT_ID", nullable=false, precision=9, scale=0) ), 
        @AttributeOverride(name="customerId", column=@Column(name="CUSTOMER_ID", nullable=false, precision=9, scale=0) ) } )
    public CustomerSaleProductId getId() {
        return this.id;
    }
    
    public void setId(CustomerSaleProductId id) {
        this.id = id;
    }




}


