package org.javautil.sales.dto;
// Generated Sep 8, 2011 2:57:23 PM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sale generated by hbm2java
 */
@Entity
@Table(name="SALE"
    ,schema="PUBLIC"
    ,catalog="SALES"
)
public class Sale  implements java.io.Serializable {


     private Long saleId;
     private Product product;
     private Customer customer;
     private Date shipDt;
     private BigDecimal qty;

    public Sale() {
    }

    public Sale(Product product, Customer customer, Date shipDt, BigDecimal qty) {
       this.product = product;
       this.customer = customer;
       this.shipDt = shipDt;
       this.qty = qty;
    }
   
     @SequenceGenerator(name="generator", sequenceName="SALE_NBR_SEQ")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")
    
    @Column(name="SALE_ID", nullable=false, precision=18, scale=0)
    public Long getSaleId() {
        return this.saleId;
    }
    
    public void setSaleId(Long saleId) {
        this.saleId = saleId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PRODUCT_ID", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CUSTOMER_ID", nullable=false)
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="SHIP_DT", nullable=false, length=8)
    public Date getShipDt() {
        return this.shipDt;
    }
    
    public void setShipDt(Date shipDt) {
        this.shipDt = shipDt;
    }
    
    @Column(name="QTY", nullable=false, precision=13, scale=5)
    public BigDecimal getQty() {
        return this.qty;
    }
    
    public void setQty(BigDecimal qty) {
        this.qty = qty;
    }




}


