CREATE TABLE UT_ADDR_VALIDATE ( 
	UT_ADDR_VALIDATE_NBR  NUMBER(18)	NOT NULL, 
	RUN_NBR               NUMBER(9)	NOT NULL, 
	DATA_SRC_NBR          NUMBER(9)	NOT NULL, 
	DATA_SRC_PK           NUMBER(18)	NOT NULL, 
	NAME                  VARCHAR2(40), 
	RAW_ADDR_1            VARCHAR2(35), 
	RAW_ADDR_2            VARCHAR2(35), 
	RAW_ADDR_3            VARCHAR2(35), 
	RAW_CITY              VARCHAR2(25), 
	RAW_STATE_CD          VARCHAR2(5), 
	RAW_CNTRY_CD          VARCHAR2(3), 
	RAW_POSTAL_CD         VARCHAR2(10), 
	STD_PO_BOX            VARCHAR2(20), 
	STD_STREET_NAME       VARCHAR2(35), 
	STD_STREET_NBR        VARCHAR2(12), 
	STD_STREET_TYPE       VARCHAR2(12), 
	STD_SUBUNIT_CD        VARCHAR2(20), 
	STD_SUBUNIT_TYPE      VARCHAR2(10), 
	STD_ADDR_1            VARCHAR2(40), 
	STD_ADDR_2            VARCHAR2(40), 
	STD_CITY              VARCHAR2(40), 
	STD_STATE_CD          VARCHAR2(4), 
	STD_POSTAL_CD         VARCHAR2(10), 
	AUTH_ADDR_1           VARCHAR2(50), 
	AUTH_ADDR_2           VARCHAR2(50), 
	AUTH_CITY             VARCHAR2(40), 
	AUTH_STATE_CD         VARCHAR2(4), 
	AUTH_POSTAL_CD        VARCHAR2(10), 
	AUTH_RQST_CD          VARCHAR2(1), 
	STD_AUTH_ADDR_1       VARCHAR2(40), 
	STD_AUTH_ADDR_2       VARCHAR2(40), 
	STD_AUTH_CITY         VARCHAR2(40), 
	STD_AUTH_STATE_CD     VARCHAR2(4), 
	STD_AUTH_POSTAL_CD    VARCHAR2(10), 
	STD_TS                DATE, 
	STD_ERR_MSG           VARCHAR2(256), 
	AUTH_ERR_MSG          VARCHAR2(256), 
	STD_AUTH_ERR_MSG      VARCHAR2(256), 
	SRC_COMMENT           VARCHAR2(10), 
	SRC_INVALID_FLG       VARCHAR2(1), 
	AUTH_LATITUDE         NUMBER(9,6), 
	AUTH_LONGITUDE        NUMBER(9,6)
);
	
ALTER TABLE UT_ADDR_VALIDATE ADD 
			 CONSTRAINT UT_ADDR_VALIDATE_PK PRIMARY KEY 
			 (UT_ADDR_VALIDATE_NBR) ;

ALTER TABLE UT_ADDR_VALIDATE ADD 
			 CONSTRAINT UAV_DATA_SRC_UK 
			 UNIQUE (DATA_SRC_NBR, DATA_SRC_PK) ;

create sequence ut_addr_validate_seq;
