//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.09 at 01:38:12 PM EDT 
//

package org.javautil.table;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for primaryKey complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="primaryKey">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="constraintName" type="{http://www.javautil.org/Table/}dbName"/>
 *         &lt;element name="NewElement" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "primaryKey", propOrder = { "constraintName", "newElement" })
public class PrimaryKey {

	@XmlElement(required = true)
	protected String constraintName;
	@XmlElement(name = "NewElement", required = true)
	protected String newElement;

	/**
	 * Gets the value of the constraintName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getConstraintName() {
		return constraintName;
	}

	/**
	 * Sets the value of the constraintName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setConstraintName(final String value) {
		this.constraintName = value;
	}

	/**
	 * Gets the value of the newElement property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNewElement() {
		return newElement;
	}

	/**
	 * Sets the value of the newElement property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNewElement(final String value) {
		this.newElement = value;
	}

}
