//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.09 at 01:38:12 PM EDT 
//

package org.javautil.datasources;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the org.javautil.datasources package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _Datasources_QNAME = new QName(
			"http://datasources.javautil.org", "datasources");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: org.javautil.datasources
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link DatasourceType }
	 * 
	 */
	public DatasourceType createDatasourceType() {
		return new DatasourceType();
	}

	/**
	 * Create an instance of {@link Property }
	 * 
	 */
	public Property createProperty() {
		return new Property();
	}

	/**
	 * Create an instance of {@link SystemProperty }
	 * 
	 */
	public SystemProperty createSystemProperty() {
		return new SystemProperty();
	}

	/**
	 * Create an instance of {@link Datasources }
	 * 
	 */
	public Datasources createDatasources() {
		return new Datasources();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Datasources }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://datasources.javautil.org", name = "datasources")
	public JAXBElement<Datasources> createDatasources(final Datasources value) {
		return new JAXBElement<Datasources>(_Datasources_QNAME,
				Datasources.class, null, value);
	}

}
