//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.09 at 01:38:12 PM EDT 
//

package org.javautil.datasources;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for property complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="property">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sys" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="env" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="encryptedValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/choice>
 *       &lt;attribute name="key" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "property", propOrder = { "value", "sys", "env",
		"encryptedValue" })
public class Property {

	protected String value;
	protected String sys;
	protected String env;
	protected String encryptedValue;
	@XmlAttribute(required = true)
	protected String key;

	/**
	 * Gets the value of the value property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getValue() {
		return value;
	}

	/**
	 * Sets the value of the value property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setValue(final String value) {
		this.value = value;
	}

	/**
	 * Gets the value of the sys property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSys() {
		return sys;
	}

	/**
	 * Sets the value of the sys property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSys(final String value) {
		this.sys = value;
	}

	/**
	 * Gets the value of the env property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEnv() {
		return env;
	}

	/**
	 * Sets the value of the env property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEnv(final String value) {
		this.env = value;
	}

	/**
	 * Gets the value of the encryptedValue property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEncryptedValue() {
		return encryptedValue;
	}

	/**
	 * Sets the value of the encryptedValue property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEncryptedValue(final String value) {
		this.encryptedValue = value;
	}

	/**
	 * Gets the value of the key property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getKey() {
		return key;
	}

	/**
	 * Sets the value of the key property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setKey(final String value) {
		this.key = value;
	}

}
